# Generated by Django 5.2.3 on 2025-06-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediacontent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media kontent', 'verbose_name_plural': 'Barcha kontentlar'},
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='content_type',
            field=models.CharField(choices=[('article', 'Maqola'), ('image', 'Rasm'), ('audio', 'Audio'), ('video', 'Video')], max_length=20, verbose_name='Kontent turi'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
    ]
