# Generated by Django 5.2.3 on 2025-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_mediacontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kategoriya'),
        ),
    ]
