# Generated by Django 5.2.3 on 2025-06-20 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_mediacontent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismingiz')),
                ('text', models.TextField(verbose_name='Fikr matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan vaqti')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.mediacontent')),
            ],
        ),
    ]
