# Generated by Django 5.2.3 on 2025-06-20 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_comment_options_alter_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediacontent',
            options={'ordering': ['-publish_time'], 'verbose_name': 'Media kontent', 'verbose_name_plural': 'Barcha kontentlar'},
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol (saytda ko‘rinsinmi?)'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Chop etish vaqti'),
        ),
    ]
