# Generated by Django 5.2.3 on 2025-06-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_mediacontent_options_mediacontent_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ko‘rishlar soni'),
        ),
        migrations.CreateModel(
            name='ViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Foydalanuvchi IP manzili')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Ko‘rilgan vaqt')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='content.mediacontent')),
            ],
            options={
                'verbose_name': 'Ko‘rish logi',
                'verbose_name_plural': 'Ko‘rishlar logi',
                'ordering': ['-viewed_at'],
                'unique_together': {('content', 'ip_address')},
            },
        ),
    ]
